// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zjuudzqbzmlcupjsmzrf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpqdXVkenFiem1sY3VwanNtenJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxOTg1NjcsImV4cCI6MjA2Nzc3NDU2N30.9dCuO-heEPsbEgRadn-xYzr-eOQlZiA1CQjT75CBQWk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});